--- #YAML:1.0
name: Tie-RefHash-Weak
version: 0.01
author:
  - Yuval Kogman <nothingmuch@woobling.org>
abstract: |-
  A Tie::RefHash subclass with weakened references in the keys.
license: perl
requires:
  Scalar::Util: 0
  perl: '>= 5.6'
build_requires:
  Test::More: 0
provides:
  Tie::RefHash::Weak:
    file: lib/Tie/RefHash/Weak.pm
    version: 0.01
generated_by: Module::Build version 0.250.0
