--- #YAML:1.0
name:                Tie-RefHash-Weak
version:             0.09
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Scalar::Util:                  0
    Task::Weaken:                  0
    Tie::RefHash:                  1.34
    Variable::Magic:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
